
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: slavik
  password: 1111
  
development:
  <<: *default
  database: betonnalavka_dev
  
development:
  <<: *default
  database: betonnalavka_test


production:
  <<: *default
  database: betonnalavka_prod

