
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: slavik

development:
  <<: *default
  database: betonnalavka_dev
  
development:
  <<: *default
  database: betonnalavka_test


production:
  <<: *default
  database: betonnalavka_prod
  username: slavik
  password: <%= ENV['MYAPP_DATABASE_PASSWORD'] %>
  host: https://dashboard.heroku.com
